---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deploy
  namespace: ${namespace}
 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-deploy-admin-role
  namespace: ${namespace}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "configmaps", "secrets", "services", "endpoints"]
  verbs: ["create", "delete", "get", "watch", "list", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "watch", "list", "patch", "update"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["create", "delete", "get", "watch", "list", "patch", "update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create", "delete", "get", "watch", "list", "patch", "update"]
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-admin-role-binding
  namespace: ${namespace}
subjects:
- kind: ServiceAccount
  name: jenkins-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deploy-admin-role