kind: ServiceAccount
apiVersion: v1
metadata:
  name: orchestratorsaccnt
  namespace: boa-y80-pdy-sim-03
  selfLink: /api/v1/namespaces/boa-y80-pdy-sim-03/serviceaccounts/orchestratorsaccnt
secrets:
  - name: orchestratorsaccnt-token-vplgx
  - name: orchestratorsaccnt-token-crz8m


kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestratorrole
  namespace: boa-y80-pdy-sim-03
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/namespaces/boa-y80-pdy-sim-03/roles/orchestratorrole
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - endpoints
      - pods
      - services
      - secrets


kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestratorrolebinding
  namespace: boa-y80-pdy-sim-03
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/namespaces/boa-y80-pdy-sim-03/rolebindings/orchestratorrolebinding
subjects:
  - kind: ServiceAccount
    name: orchestratorsaccnt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestratorrole
