REPLACE MACRO PDY_PDML_IHM_${sid}.MM_BATCH_TRACE(batchName VARCHAR(20),executionId BIGINT,batchState VARCHAR(15) ,debutExecutionBatch TIMESTAMP(6), finExecutionBatch TIMESTAMP(6)  ) AS ( 
LOCK TABLE PDY_PDML_IHM_${sid}.T_BATCH_ORCHESTRATOR FOR WRITE 	
MERGE INTO PDY_PDML_IHM_${sid}.T_BATCH_TRACE  AS BATCH_TRACE
USING
( SELECT :batchName as BATCH_NAME  ,:executionId as ID_EXECUTION,:batchState as BATCH_STATE , :debutExecutionBatch as DH_DEBUT_EXEC_BATCH ,:finExecutionBatch as DH_FIN_EXEC_BATCH ) as PARAM
ON 
  BATCH_TRACE.BATCH_NAME = PARAM.BATCH_NAME
  AND BATCH_TRACE.ID_EXECUTION = PARAM.ID_EXECUTION
WHEN MATCHED
THEN UPDATE
	SET 
		DH_FIN_EXEC_BATCH = PARAM.DH_FIN_EXEC_BATCH,
		BATCH_STATE = PARAM.BATCH_STATE
WHEN NOT MATCHED 
THEN INSERT (BATCH_NAME, ID_EXECUTION,BATCH_STATE, DH_DEBUT_EXEC_BATCH,DH_FIN_EXEC_BATCH)
	VALUES
	(PARAM.BATCH_NAME, PARAM.ID_EXECUTION,PARAM.BATCH_STATE, PARAM.DH_DEBUT_EXEC_BATCH,PARAM.DH_FIN_EXEC_BATCH);
);