 REPLACE MACRO PDY_PDML_IHM_${sid}.MS_GET_BATCH_METADATA(BATCH_NAME VARCHAR(15)  ) AS ( 
LOCK TABLE PDY_PDML_IHM_${sid}.T_BATCH_ORCHESTRATOR FOR ACCESS 
SELECT 
     BATCH_NAME 
     , SEQUENCE_NUMERATOR 
     , STEP_NAME 
	 ,STEP_DESCRIPTION
	 , STEP_TYPE
	 ,SECRET_NAME
	 ,TARGET_TABLE
     , STEP_INIT 
	 , STEP_MAIN 
	 ,STEP_CLOSURE
	 ,MAX(SEQUENCE_NUMERATOR)  OVER (PARTITION BY 1 )  AS SEQUENCE_NUMBER
	 ,COUNT(STEP_NAME)  OVER (PARTITION BY SEQUENCE_NUMERATOR )  AS STEP_NUMBER
FROM PDY_PDML_IHM_${sid}.T_BATCH_ORCHESTRATOR 
WHERE BATCH_NAME = :BATCH_NAME 
ORDER BY SEQUENCE_NUMERATOR;

);